project:
  type: website

website:
  title: "Excel PowerQuery Intro"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: tips_and_tricks.qmd
        text: Tips and Tricks
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



