---
title: "Excel PowerQuery Intro"
format: 
    html:
        toc: true
        css: styles.css
---

## A quick review of relational database

* Relational Database (RDBMS)
    + [Relational model](https://en.wikipedia.org/wiki/Relational_model):
        - Developed by Edgar F. Codd
        - Based on the mathematical concept of relations
    + SQL (Structured Query Language):
        - Initially called SEQUEL (Structured English Query Language)
        - Based on [relational algerbra](https://en.wikipedia.org/wiki/Relational_algebra)
    + Elements of modern RDBMS:
        - Tables (Tables): collection of relations
        - Columns (Fields / Attributes): a variable (with the associated data type). 
        - Rows (Record): a distinct collection of attributes
        - Primary Key: a column that contains a unique value for each record
        - Foreign Key: a column that references the primary key in another table
        - Index: additional data structure that associates an identifier with a row and/or a column (Excel row or column number)

### Codd's Third Normal Form (3NF): 
* Developed to improve the efficiency of a database system.
1. **No repeating groups of data. Separate repeating data into tables.**

:::{.columns style='display: flex !important;'}
::::{.column width="45%"}
| Student          | College | Major            | Score |
|------------------|-----|------------------|-----|-----|
| Alice | L&S | Computer Science | 60 |
| Alice | L&S | Computer Science | 70 |
| Bob | Ag  | Economics       | 65 |
| Cathy| CBS  | Biology         | 90 |
::::
::::{.column width="10%" style='display: flex; justify-content: center; align-items: center;'}
 =>
::::
::::{.column width="45%"}
| Student          | Test | Score |
|------------------|-----|-----|
| Alice | Midterm  | 60 |
| Alice | Final | 70 |
| Bob | Midterm | 65 |
| Cathy| Midterm | 90 |

| Student | College | Major |
|----|----|------|
| Alice | L&S | Computer Science |
| Bob | Ag | Economics |
| Cathy | CBS| Biology |
::::
:::

2. **All non-key columns are only dependent on the primary key.**

:::{.columns style='display: flex !important;'}
::::{.column width="45%"}
| Student | College | Major |
|----|----|------|
| Alice | L&S | Computer Science |
| Bob | Ag | Economics |
| Cathy | CBS| Biology |
::::

::::{.column width="10%" style='display: flex; justify-content: center; align-items: center;'}
\rightarrow
::::

::::{.column width="45%"}
| Student |Major |
|----|-----|
| Alice | Computer Science |
| Bob | Economics |
| Cathy | Biology |

| College | Major |
|-----|------|
| L&S | Computer Science |
| Ag | Economics |
| CBS | Biology |
::::
:::

3. **No transitive dependence. If field A is dependent on B, and B is dependent on C, then one of the relations can be extracted into another table.**

:::{.columns style='display: flex !important;'}
::::{.column width="45%"}
| Student | College | Major | Major Code |
|----|----|------|----| 
| Alice | L&S | Computer Science | LCOM |
| Bob | Ag | Economics | AECO |
| Cathy | CBS| Biology | CBIO |
::::

::::{.column width="10%" style='display: flex; justify-content: center; align-items: center;'}
 \rightarrow
::::

::::{.column width="45%"}
| Student | Major Code |
|----|----| 
| Alice | LCOM |
| Bob | AECO |
| Cathy | CBIO |

| Major | Major Code |
|----|----| 
| Computer Science | LCOM |
| Economics | AECO |
| Biology | CBIO |

| College | Major |
|-----|------|
| L&S | Computer Science |
| Ag | Economics |
| CBS | Biology |

::::
:::

### Hadley Wickham's [*tidy data*](https://www.jstatsoft.org/article/view/v059i10):
1. Each variable forms a column.
2. Each observation forms a row.
3. Each type of observational unit forms a table.

##### Example of a messy data set (also known as wide format)

| year | artist | track | time | date.entered | wk1 | wk2 | wk3|
|---|---|---|---|---|---|---|---| 
| 2000 | 2 Pac | Baby Don’t Cry | 4:22 | 2000-02-26 | 87 | 82 | 72 |
| 2000 | 2Ge+her | The Hardest Part Of ... | 3:15 | 2000-09-02 | 91 | 87 | 92 |

 \downarrow

#### Example of a tidy data set (also known as tall format)

| year | artist | time | track | date | week | rank |
|---|---|---|---|---|---|---|
| 2000 | 2 Pac | 4:22 | Baby Don’t Cry | 2000-02-26 |  1 | 87 |
| 2000 | 2 Pac | 4:22 | Baby Don’t Cry | 2000-03-04 |  2 | 82 |
| 2000 | 2 Pac | 4:22 | Baby Don’t Cry | 2000-03-11 | 3 | 72 |
| 2000 | 2Ge+her | 3:15 | The Hardest Part Of ... | 2000-09-02 | 1 | 91 |
| 2000 | 2Ge+her | 3:15 | The Hardest Part Of ... | 2000-09-09 | 2 | 87 |
| 2000 | 2Ge+her | 3:15 | The Hardest Part Of ... | 2000-09-16 | 3 | 92 |


## Data pipeline
```{mermaid}
---
title: Data Pipeline
---
flowchart TB
    A[data entry] --> D{data ingestion}
    B[sensors] --> D
    C[applications] --> D
    D --> E["data warehouse"]
    E --> F{Extract Transform Load}
    F --> G[reports]
    F --> H[dashboards]
    F --> I[predictive models]

```

### ETL Extract, Transform, Load
* Actions to transform data into Codd's 3NF:
    + Create new tables by subsetting columns (SELECT) and remove duplicates (DISTINCT)
    + Update the original columns by creating new foreign key columns (ADD COLUMN) and remove redunant columns
* Actions to transform data from Codd's 3NF:
    + Merge (known as JOIN in relational algebra)
* Tools for extracting and transforming data:
    + Pivot (tranform data from tall to wide)
    + Unpivot (transform data from wide to tall)
    + Stack (create hierarchical index)
    + Unstack (convert hierarchical index into columns)
    + Splitting columns
    + Combining columns

## Using PowerQuery to perform ETL

Q: What is [Power Query](https://powerquery.microsoft.com/en-us/){target='_blank'}?
A: Microsoft’s Data Connectivity and Data Preparation technology that lets you seamlessly access data stored in hundreds of sources and reshape it to fit your needs—all with an easy to use, engaging, no-code experience. 

* Coding is not required
* The underlying code is available to check for correctness and reproducibility 
* Coding can be done to perform more complex analysis

### Excel Version
* It is recommended to use the latest version of Excel to access all the latest features. Download from [office.ucdavis.edu](https://office.ucdavis.edu).
* Sample files are listed here:
    - [names](data/names.xlsx)
    - [transaction](data/transactions.xlsx)
    - [power_query_examples](data/power_query_examples.xlsx)



### Sourcing data

* Data sources can be other Excel files, files, a database connection, or other data sources.

#### How to:

1. Go to the **Data** tab. 
2. Click on the top left button *Get Data (Power Query)*. 
3. Choose the data source. (For this example, import from Excel and connect to the source data file.)
4. Promote headers if the first row of data contains headers. Otherwise, manually rename columns. 

#### Best practices

* Always confirm column names, set data types for each columns. (Make sure to *always* set dollar values as Currency.) 
* Set key columns as needed.
* Perform subsequent queries by referencing on the initial connection. Minimize the number of outside connections. 
    - In the PowerQuery Editor, right-click on the query and create a *reference*.

#### Try: 
1. Load data from the [names.xlsx](data/names.xlsx) file and from the [transactions.xlsx](data/transactions.xlsx) file.

### Merging tables (JOIN)
* [Primer on SQL JOIN (Wikipedia)](https://en.wikipedia.org/wiki/Join_(SQL)){target='_blank'}
* [PowerQuery References on Table.Join](https://learn.microsoft.com/en-us/powerquery-m/table-join){target='_blank'}

#### Full Outer Join
* Sequence 

#### Inner Join

#### Left Outer Join Example

#### Left Anti Join Example

### Filter rows 

### Aggregate data with GROUP BY

### Pivot and Unpivot data

### Custom queries (Power Query M formula language)

## Exporting
* Power BI
* Power Pivot
* Copy/Paste